-- Dettagli di un lavoro in corso, in forma strutturata.
--
-- Il messaggio è una frase per la riga del pannello; questo è il resto — quante
-- unità sono fatte, quanti byte sono arrivati, quanti se ne prevedono, con che
-- risoluzione, verso quale host. Ogni tipo di lavoro ci mette le sue chiavi e
-- l'interfaccia mostra quelle che conosce: uno scaricamento parla di carte e
-- megabyte, una verifica di file integri e orfani.
--
-- JSON e non colonne perché le chiavi cambiano con il tipo di lavoro: una
-- colonna per ogni cosa che un futuro gestore vorrà dire diventerebbe una
-- tabella piena di caselle vuote.
ALTER TABLE jobs ADD COLUMN detail TEXT;
